### ISSUE TITLE
/ypspur_ros/cmd_velについて

### ISSUE THREAD

**Issue by shibuya-bitvalley** [shibuya-bitvalley/icart-mini#1]
launchファイルの追加に手間取り、連絡が遅くなってしまいました・・・

昨日ご連絡いただいた手順で動作テストを行いました
結果は以下のとおりです
![ypspur_roscmd_vel](https://user-images.githubusercontent.com/29628346/30103004-512cc410-932c-11e7-87b0-8de306135197.png)

**Comment by RyodoTanaka** [comment]
@shibuya-bitvalley 
お返事遅くなってすみません...
そのログだと，やはり値が入っていないようですね...
原因を探ってみます

**Comment by RyodoTanaka** [comment]
@shibuya-bitvalley 
https://github.com/shibuya-bitvalley/icart-mini/blob/10a375f280ee14d027ea165924842cafb7e4aa9d/src/icart_pkg/src/my_joystick.cpp#L35-L36
上記の部分で速度指令を計算していることになりますが，
`a_scale_`と`l_scale_`により，そのスケールをいじっています．
この，`a_scale_`と`l_scale_`は，
https://github.com/shibuya-bitvalley/icart-mini/blob/10a375f280ee14d027ea165924842cafb7e4aa9d/src/icart_pkg/src/my_joystick.cpp#L22-L23
上記の部分で`scale_angular`と`scale_linear`という名前のparameterを取得し，代入しています．
ソースコードを見る限りでは，このparameterが設定されておらず，結果として`a_scale_`と`l_scale_`が不定となり，今回の場合はおそらくどちらも`0`のままになっていると考えられます．

対策方法は，parameterを設定するだけです．
rosparamをコマンドから直接設定しても良いのですが，毎回やるのはとても面倒ですし，実際はそういったやり方はしません．
launchファイル内で指定する方法をとります．

下に例を示します．
以下では，joyノードの起動と，icart_teleopノードの起動をパラメータの指定付きで行っています．

```xml
<launch>
  <!-- joy_node -->
  <node pkg="joy" type="joy_node" name="joy">
  </node>

  <!-- my_joystick -->
  <node pkg="icart_pkg" type="my_joystick" name="joystick" output="screen">
    <param name="scale_angular" value="1.0" />
    <param name="scale_linear" value="1.0" />
  </node>
</launch>
```

**Comment by shibuya-bitvalley** [comment]
パラメーターを設定してみましたが値がおかしいままでした・・・
直接a_scale_とl_scale_に入れて午後試してみようと思います。

![result2](https://user-images.githubusercontent.com/29628346/30143835-bcf0b5bc-93c2-11e7-9fd5-96a6732c8018.png)

**Comment by RyodoTanaka** [comment]
@shibuya-bitvalley 
そのやり方で良いと思います！
もしそれでも変わらなかったら，`axis_linear`と`axis_angular`の値がおかしいと思われます．
この`axis_linear`と`axis_angular`は，`/joy`トピックメッセージに格納されている配列データの何番目をそれぞれ`linear`と`anbular`の入力値にするのか，を設定するものです．
調べ方としては，`joy`ノードのみを起動し，
```bash
$ rostopic echo /joy
```
を起動した後，実際に動かしたいコントローラを動かしながら，値を取り出したい配列のインデックスを数える．
という方法です．
